"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Run = { id: string; entity_type: "manufacturers" | "categories" | "features" | "products" | "icecat"; filters: { onlyActive?: boolean; manufacturerId?: string; categoryId?: string; featureId?: string; productId?: string; productIds?: string[]; eans?: string[]; modifiedSince?: string; forceImages?: boolean; force?: boolean; name?: string }; status: "queued" | "running" | "paused" | "stopped" | "completed" | "failed"; total_count: number; processed_count: number; created_count: number; updated_count: number; unchanged_count: number; unpublished_count: number; error_count: number; started_at: string | null; finished_at: string | null; created_at: string };
type Event = { id: number; outcome: "created" | "updated" | "error" | "status"; level: "info" | "success" | "warning" | "error"; source_entity_id: string | null; source_entity_name: string | null; shopify_resource_id: string | null; message: string; created_at: string };
type EventFilter = "all" | "created" | "unpublished" | "error";

export default function CatalogExecutionPage() {
  const { id } = useParams<{ id: string }>();
  const [run, setRun] = useState<Run | null>(null);
  const [events, setEvents] = useState<Event[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [eventFilter, setEventFilter] = useState<EventFilter>("all");
  useEffect(() => { const supabase = createClient(); Promise.all([supabase.from("catalog_import_runs").select("*").eq("id", id).maybeSingle(), supabase.from("catalog_import_events").select("*").eq("run_id", id).order("id", { ascending: true })]).then(([runResult, eventsResult]) => { if (runResult.error || !runResult.data) setError("No se encontró esta ejecución."); else setRun(runResult.data as Run); setEvents((eventsResult.data ?? []) as Event[]); }); }, [id]);
  const visibleEvents = useMemo(() => events.filter((event) => eventFilter === "all" || eventFilter === "created" && event.outcome === "created" || eventFilter === "unpublished" && event.outcome === "updated" && event.message.includes("retirada") || eventFilter === "error" && event.outcome === "error"), [eventFilter, events]);
  const importHref = run?.entity_type === "icecat" ? "/importacion-icecat" : "/importacion-catalogo";
  const importName = run?.entity_type === "icecat" ? "importación Icecat" : "importación catálogo";
  if (error) return <main className="mx-auto w-full max-w-4xl px-6 py-16"><a href={importHref} className="text-emerald-700 underline">← Volver a {importName}</a><p className="mt-6 rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</p></main>;
  if (!run) return <main className="mx-auto w-full max-w-4xl px-6 py-16 text-zinc-500">Cargando ejecución…</main>;
  const metrics = run.entity_type === "icecat" ? <><Counter label="Procesados" value={`${run.processed_count}/${run.total_count}`} /><Counter label="Añadidos" value={run.created_count} /><Counter label="Actualizados" value={run.updated_count} /><Counter label="Sin datos o cambios" value={run.unchanged_count} /><Counter label="Pendientes" value={Math.max(0, run.total_count - run.processed_count)} /><Counter label="Errores" value={run.error_count} /></> : <><Counter label="Procesadas" value={`${run.processed_count}/${run.total_count}`} /><Counter label={run.entity_type === "products" ? "Creados" : "Creadas"} value={run.created_count} /><Counter label={run.entity_type === "products" ? "Actualizados" : "Actualizadas"} value={run.updated_count} /><Counter label="Sin cambios" value={run.unchanged_count} /><Counter label={run.entity_type === "products" ? "Desactivados" : "Desactivadas"} value={run.unpublished_count} /><Counter label="Errores" value={run.error_count} /></>;
  return <main className="mx-auto w-full max-w-5xl px-6 py-12 pb-16"><a href={importHref} className="text-sm font-medium text-emerald-700 underline underline-offset-2">← Volver a {importName}</a><header className="mt-6"><p className="text-sm font-semibold tracking-[0.18em] text-emerald-700 uppercase">Historial</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{scopeLabel(run)}</h1><p className="mt-3 text-zinc-600">Iniciada: {dateTime(run.created_at)} · <span className="font-medium">{status(run.status)}</span> · {duration(run)}</p></header><section className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{metrics}</section><section className="mt-8 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><h2 className="text-xl font-semibold">Registro completo</h2><label className="text-sm font-medium text-zinc-700">Mostrar<select value={eventFilter} onChange={(event) => setEventFilter(event.target.value as EventFilter)} className="mt-1 block h-10 rounded-lg border border-zinc-300 bg-white px-3 font-normal text-zinc-800"><option value="all">Todos</option><option value="created">{run.entity_type === "icecat" ? "Añadidos" : "Creadas"}</option><option value="updated">{run.entity_type === "icecat" ? "Actualizados" : "Actualizadas"}</option>{run.entity_type !== "icecat" && <option value="unpublished">Desactivadas</option>}<option value="error">Errores</option></select></label></div><ul className="mt-4 divide-y divide-zinc-100 overflow-hidden rounded-xl border border-zinc-200">{visibleEvents.length ? visibleEvents.map((event) => <li key={event.id} className="p-4 text-sm"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><span className={`font-semibold ${event.outcome === "created" ? "text-emerald-700" : event.outcome === "updated" ? "text-amber-700" : event.outcome === "error" ? "text-red-700" : "text-zinc-700"}`}>{eventLabel(event, run.entity_type)}</span>{event.source_entity_id && <span>{run.entity_type === "categories" ? "Categoría" : run.entity_type === "features" ? "Característica" : "Producto"} #{event.source_entity_id}</span>}{event.source_entity_name && <span className="text-zinc-600">{event.source_entity_name}</span>}<time className="ml-auto text-zinc-400">{dateTime(event.created_at)}</time></div><p className="mt-1 text-zinc-600">{event.message}</p></li>) : <li className="p-4 text-sm text-zinc-500">No hay resultados para este filtro.</li>}</ul></section></main>;
}

function scopeLabel(run: Run) { const filters = run.filters; const productFilter = filters.productIds?.length ? filters.productIds.join(", ") : filters.productId; const text = [filters.manufacturerId ? `ID ${filters.manufacturerId}` : filters.categoryId ? `ID ${filters.categoryId}` : filters.featureId ? `ID ${filters.featureId}` : productFilter ? `SKU: ${productFilter}` : filters.eans?.length ? `EAN: ${filters.eans.join(", ")}` : ""].filter(Boolean).join(" · "); const entity = run.entity_type === "icecat" ? "Icecat" : run.entity_type === "categories" ? "Categorías" : run.entity_type === "features" ? "Características" : run.entity_type === "products" ? "Productos" : "Marcas"; return `${entity}${text ? `: ${text}` : run.entity_type === "manufacturers" && filters.onlyActive === false ? " (todas)" : run.entity_type === "manufacturers" ? " activas" : ""}`; }
function status(value: Run["status"]) { return ({ queued: "En cola", running: "En marcha", paused: "Pausada", stopped: "Detenida", completed: "Completada", failed: "Con error" } as const)[value]; }
function eventLabel(event: Event, entity: Run["entity_type"]) { if (entity === "icecat") return ({ created: "Añadido", updated: "Actualizado", error: "Error", status: "Estado" } as const)[event.outcome]; if (event.outcome === "updated" && entity === "categories") return event.message.includes("retirada") ? "Desactivada" : "Sin cambios"; if (event.outcome === "updated" && (entity === "manufacturers" || entity === "features") && event.message.includes("sin cambios")) return "Sin cambios"; if (entity === "products" && event.outcome === "updated" && event.message.includes("archivado")) return "Desactivado"; if (entity === "products") return ({ created: "Creado", updated: "Actualizado", error: "Error", status: "Estado" } as const)[event.outcome]; return ({ created: "Creada", updated: "Actualizada", error: "Error", status: "Estado" } as const)[event.outcome]; }
function dateTime(value: string) { return new Intl.DateTimeFormat("es-ES", { timeZone: "Europe/Madrid", dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
function duration(run: Run) { if (!run.started_at) return "Sin iniciar"; const end = run.finished_at ? new Date(run.finished_at).getTime() : Date.now(); const seconds = Math.max(0, Math.round((end - new Date(run.started_at).getTime()) / 1_000)); return seconds < 60 ? `Duración: ${seconds} s` : `Duración: ${Math.floor(seconds / 60)} min ${seconds % 60 ? `${seconds % 60} s` : ""}`; }
function Counter({ label, value }: { label: string; value: string | number }) { const visibleLabel = label === "Procesadas" ? "Procesados" : label; return <div className="rounded-xl border border-zinc-200 bg-white p-3 shadow-sm sm:p-4"><p className="text-sm text-zinc-500">{visibleLabel}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>; }
