"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";
import { createClient } from "@/lib/supabase/client";

type Status = "queued" | "running" | "paused" | "stopped" | "completed" | "failed";
type Run = { id: string; filters: { productIds?: string[]; eans?: string[]; force?: boolean }; status: Status; total_count: number; processed_count: number; created_count: number; updated_count: number; unchanged_count: number; error_count: number; created_at: string; started_at: string | null; finished_at: string | null };
type Event = { id: number; outcome: "created" | "updated" | "error" | "status"; source_entity_id: string | null; source_entity_name: string | null; message: string; created_at: string };

export default function IcecatImportPage() {
  const [skus, setSkus] = useState(""); const [eans, setEans] = useState(""); const [force, setForce] = useState(false); const [run, setRun] = useState<Run | null>(null); const [history, setHistory] = useState<Run[]>([]); const [events, setEvents] = useState<Event[]>([]); const [logsExpanded, setLogsExpanded] = useState(false); const [userEmail, setUserEmail] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [starting, setStarting] = useState(false); const [changing, setChanging] = useState(false); const [error, setError] = useState<string | null>(null);
  const loadEvents = useCallback(async (runId: string) => { const { data } = await createClient().from("catalog_import_events").select("*").eq("run_id", runId).order("id", { ascending: true }).limit(300); setEvents((data ?? []) as Event[]); }, []);
  const load = useCallback(async () => {
    const response = await fetch("/api/catalog/runs?entityType=icecat", { cache: "no-store" }); const body = await response.json();
    if (!response.ok) { setError(body.error ?? "No se pudo cargar el historial."); setLoading(false); return; }
    const runs = body.runs as Run[]; setHistory(runs); setRun((selected) => { const next = selected ? runs.find((item) => item.id === selected.id) ?? runs[0] ?? null : runs[0] ?? null; if (next) void loadEvents(next.id); return next; }); setLoading(false);
  }, [loadEvents]);
  useEffect(() => { void load(); createClient().auth.getUser().then(({ data }) => setUserEmail(data.user?.email ?? null)); }, [load]);
  useEffect(() => {
    if (!run) return; const supabase = createClient(); const channel = supabase.channel(`icecat-${run.id}`).on("postgres_changes", { event: "*", schema: "public", table: "catalog_import_runs", filter: `id=eq.${run.id}` }, () => { void load(); }).on("postgres_changes", { event: "INSERT", schema: "public", table: "catalog_import_events", filter: `run_id=eq.${run.id}` }, () => { void loadEvents(run.id); }).subscribe(); const timer = ["queued", "running"].includes(run.status) ? window.setInterval(() => { void load(); }, 3_000) : undefined; return () => { if (timer) window.clearInterval(timer); void supabase.removeChannel(channel); };
  }, [load, loadEvents, run]);
  async function start(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStarting(true); setError(null); try { const response = await fetch("/api/catalog/runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entityType: "icecat", skus, eans, force }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "No se pudo iniciar la importación."); setRun(body.run); setHistory((items) => [body.run, ...items.filter((item) => item.id !== body.run.id)]); setEvents([]); setLogsExpanded(true); await loadEvents(body.run.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "Error inesperado."); } finally { setStarting(false); } }
  async function changeStatus(status: "paused" | "stopped" | "queued") { if (!run) return; setChanging(true); setError(null); try { const response = await fetch(`/api/catalog/runs/${run.id}/status`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "No se pudo actualizar la ejecución."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Error inesperado."); } finally { setChanging(false); } }
  const active = Boolean(run && ["queued", "running", "paused"].includes(run.status)); const progress = run?.total_count ? Math.round((run.processed_count / run.total_count) * 100) : 0; const elapsed = run?.started_at ? Math.max(0, (run.finished_at ? new Date(run.finished_at).getTime() : Date.now()) - new Date(run.started_at).getTime()) : null; const estimate = run ? remainingEstimate(run, events) : null; const timingText = elapsed === null ? "Esperando a que comience el proceso…" : run?.status === "completed" ? `Importación completada · duración: ${formatDuration(elapsed)}.` : estimate ? `Tiempo transcurrido: ${formatDuration(elapsed)} · restante estimado: ${formatDuration(estimate)} · promedio: ${formatDuration(Math.round(estimate / Math.max(1, run!.total_count - run!.processed_count)))} por producto.` : `Tiempo transcurrido: ${formatDuration(elapsed)} · calculando el tiempo restante…`;
  return <div className="min-h-screen bg-zinc-50 lg:grid lg:grid-cols-[15rem_minmax(0,1fr)]"><AppSidebar active="icecat" userEmail={userEmail} /><main className="mx-auto flex w-full max-w-5xl flex-col gap-7 px-6 pb-24 pt-28 sm:px-10 lg:mx-0 lg:py-16">
    <header><h1 className="text-4xl font-semibold tracking-tight text-zinc-950">Importación Icecat</h1><p className="mt-3 max-w-3xl text-zinc-600">Completa las fichas de Shopify con destacados y especificaciones técnicas de Icecat. El proceso continúa en segundo plano aunque cierres la pantalla.</p></header>
    <form onSubmit={start} className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><fieldset disabled={active || starting} className="space-y-5 disabled:opacity-60"><legend className="text-lg font-semibold">Alcance de la importación</legend><p className="rounded-lg bg-zinc-50 p-3 text-sm text-zinc-600">Busca primero el producto en Shopify por SKU o EAN y, si existe, completa su metafield <code>custom.icecat</code>. Si no indicas filtros, procesa el catálogo de origen con EAN.</p><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-zinc-700">SKU <span className="font-normal text-zinc-500">(opcional; varios separados por coma)</span><input value={skus} onChange={(event) => setSkus(event.target.value)} className="mt-1 block h-11 w-full rounded-lg border border-zinc-300 px-3" placeholder="Ej. PB2A0003SE, SM-A366BZKGEUB" /></label><label className="block text-sm font-medium text-zinc-700">EAN <span className="font-normal text-zinc-500">(opcional; varios separados por coma)</span><input value={eans} onChange={(event) => setEans(event.target.value)} inputMode="numeric" className="mt-1 block h-11 w-full rounded-lg border border-zinc-300 px-3" placeholder="Ej. 0840023263521" /></label></div><label className="flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950"><input checked={force} onChange={(event) => setForce(event.target.checked)} type="checkbox" className="mt-0.5 h-4 w-4" /><span><strong>Actualizar datos Icecat existentes</strong><br />Vuelve a consultar y reemplaza el metafield de los productos encontrados; si no indicas ningún filtro, actualizará todos.</span></label><button className="h-11 rounded-lg bg-emerald-700 px-5 font-medium text-white hover:bg-emerald-800 disabled:opacity-60">{starting ? "Preparando cola…" : "Iniciar importación Icecat"}</button>{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}</fieldset></form>
    {loading ? <p className="text-zinc-500">Cargando ejecuciones…</p> : run && <section className="space-y-5 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">Ejecución actual</h2><p className="mt-1 text-sm text-zinc-600">{scope(run)} · <StatusBadge status={run.status} /></p></div><div className="flex gap-2">{(run.status === "queued" || run.status === "running") && <button disabled={changing} onClick={() => changeStatus("paused")} className="rounded-lg border border-amber-300 px-4 py-2 font-medium text-amber-900 hover:bg-amber-50">Pausar</button>}{run.status === "paused" && <button disabled={changing} onClick={() => changeStatus("queued")} className="rounded-lg bg-emerald-700 px-4 py-2 font-medium text-white hover:bg-emerald-800">Reanudar</button>}{active && <button disabled={changing} onClick={() => changeStatus("stopped")} className="rounded-lg border border-red-300 px-4 py-2 font-medium text-red-800 hover:bg-red-50">Detener</button>}</div></div><div><div className="mb-2 flex justify-between text-sm font-medium"><span>{run.processed_count} de {run.total_count} productos</span><span>{progress}%</span></div><div className="h-3 overflow-hidden rounded-full bg-zinc-100"><div className="h-full bg-emerald-600 transition-all" style={{ width: `${progress}%` }} /></div><p className={`mt-3 text-sm ${run.status === "completed" ? "text-emerald-700" : "text-zinc-600"}`}>{timingText}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Counter label="Añadidos" value={run.created_count} color="text-emerald-700" /><Counter label="Actualizados" value={run.updated_count} color="text-amber-700" /><Counter label="Sin datos o cambios" value={run.unchanged_count} color="text-zinc-700" /><Counter label="Errores" value={run.error_count} color="text-red-700" /><Counter label="Pendientes" value={Math.max(0, run.total_count - run.processed_count)} color="text-zinc-700" /></div><EventList events={events} expanded={logsExpanded} onToggle={() => setLogsExpanded((value) => !value)} /></section>}
    {!loading && <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Historial de Icecat</h2><p className="mt-1 text-sm text-zinc-600">Cada ejecución conserva alcance, duración, métricas y registro detallado.</p><ul className="mt-4 divide-y divide-zinc-100 rounded-xl border border-zinc-200">{history.length ? history.map((item) => <li key={item.id}><a href={`/ejecuciones-catalogo/${item.id}`} className={`block p-4 hover:bg-zinc-50 ${run?.id === item.id ? "bg-emerald-50" : ""}`}><div className="flex flex-wrap items-center gap-x-4 gap-y-1"><span className="font-semibold text-zinc-900">{scope(item)}</span><span className="text-sm text-zinc-600">{formatDate(item.created_at)}</span><span className="text-sm text-zinc-600">{durationLabel(item)}</span><span className="ml-auto"><StatusBadge status={item.status} /></span></div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-sm text-zinc-600"><span>{item.processed_count} de {item.total_count} procesados</span><span>{item.created_count} añadidos</span><span>{item.updated_count} actualizados</span><span>{item.unchanged_count} sin cambios</span><span className={item.error_count ? "text-red-700" : undefined}>{item.error_count} errores</span></div></a></li>) : <li className="p-4 text-sm text-zinc-500">Todavía no hay ejecuciones de Icecat.</li>}</ul></section>}
  </main></div>;
}
function EventList({ events, expanded, onToggle }: { events: Event[]; expanded: boolean; onToggle: () => void }) { return <div><button type="button" onClick={onToggle} aria-expanded={expanded} className="flex w-full items-center justify-between text-left text-lg font-semibold text-zinc-950"><span>Registro en directo</span><span className="text-sm font-medium text-emerald-700">{expanded ? "Ocultar" : `Ver registro (${events.length})`}</span></button>{expanded && <div className="mt-3 max-h-[28rem] overflow-auto rounded-xl border border-zinc-200"><ul className="divide-y divide-zinc-100">{events.length ? events.map((event) => <li key={event.id} className="p-3 text-sm"><div className="flex flex-wrap gap-x-2 gap-y-1"><span className={event.outcome === "created" ? "font-semibold text-emerald-700" : event.outcome === "updated" ? "font-semibold text-amber-700" : event.outcome === "error" ? "font-semibold text-red-700" : "font-semibold text-zinc-700"}>{({ created: "Añadido", updated: "Actualizado", error: "Error", status: "Estado" } as const)[event.outcome]}</span>{event.source_entity_id && <span>Producto #{event.source_entity_id}</span>}<span className="text-zinc-600">{event.source_entity_name}</span><time className="ml-auto text-zinc-400">{formatTime(event.created_at)}</time></div><p className="mt-1 text-zinc-600">{event.message}</p></li>) : <li className="p-4 text-sm text-zinc-500">La cola está preparada. Aquí aparecerá cada resultado.</li>}</ul></div>}</div>; }
function scope(run: Run) { const filters = [run.filters.productIds?.length ? `SKU: ${run.filters.productIds.join(", ")}` : "", run.filters.eans?.length ? `EAN: ${run.filters.eans.join(", ")}` : ""].filter(Boolean); return filters.length ? filters.join(" · ") : "Todos los productos con EAN"; }
function StatusBadge({ status }: { status: Status }) { return <span className={status === "completed" ? "font-medium text-emerald-700" : status === "failed" ? "font-medium text-red-700" : "font-medium text-zinc-700"}>{({ queued: "En cola", running: "En marcha", paused: "Pausada", stopped: "Detenida", completed: "Completada", failed: "Con error" } as const)[status]}</span>; }
function Counter({ label, value, color }: { label: string; value: number; color: string }) { return <div className="rounded-xl border border-zinc-200 p-3"><p className="text-sm text-zinc-500">{label}</p><p className={`mt-1 text-2xl font-semibold ${color}`}>{value}</p></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-ES", { timeZone: "Europe/Madrid", dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
function formatTime(value: string) { return new Intl.DateTimeFormat("es-ES", { timeZone: "Europe/Madrid", timeStyle: "medium" }).format(new Date(value)); }
function remainingEstimate(run: Run, events: Event[]) { if (!run.processed_count || run.processed_count >= run.total_count) return null; const processed = events.filter((event) => event.outcome !== "status"); if (processed.length >= 2) { const recent = processed.slice(-12); const intervals = recent.slice(1).map((item, index) => new Date(item.created_at).getTime() - new Date(recent[index].created_at).getTime()).filter((value) => value >= 0 && value < 60_000); if (intervals.length) return Math.round((intervals.reduce((sum, value) => sum + value, 0) / intervals.length) * (run.total_count - run.processed_count)); } if (!run.started_at) return null; const currentElapsed = Date.now() - new Date(run.started_at).getTime(); return Math.max(0, Math.round((currentElapsed / run.processed_count) * (run.total_count - run.processed_count))); }
function formatDuration(milliseconds: number) { const seconds = Math.max(0, Math.round(milliseconds / 1_000)); return seconds < 60 ? `${seconds} s` : `${Math.floor(seconds / 60)} min${seconds % 60 ? ` ${seconds % 60} s` : ""}`; }
function durationLabel(run: Run) { if (!run.started_at) return "Sin iniciar"; const end = run.finished_at ? new Date(run.finished_at).getTime() : Date.now(); return `Duración: ${formatDuration(end - new Date(run.started_at).getTime())}`; }
