"use client";

import { useCallback, useEffect, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";
import { createClient } from "@/lib/supabase/client";

type EntityTiming = { started_at: string; completed_at?: string };
type Run = { id: string; status: "running" | "completed" | "failed"; record_counts: Record<string, number>; progress: { entity?: string; entityIndex?: number; totalEntities?: number; page?: number; expected?: number; phase?: string; entity_timings?: Record<string, EntityTiming> }; error_message: string | null; started_at: string; completed_at: string | null };
const labels: Record<string, string> = { categories: "Categorías", brands: "Marcas", products: "Productos", prices: "Precios", stock: "Stock" };

export default function MhdImportPage() {
  const [runs, setRuns] = useState<Run[]>([]); const [email, setEmail] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [starting, setStarting] = useState(false); const [now, setNow] = useState(Date.now());
  const load = useCallback(async () => { const response = await fetch("/api/mhd-catalog-import", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "No se pudo consultar MHD."); setRuns(body.runs ?? []); }, []);
  useEffect(() => { void load().catch((caught) => setError(caught.message)); createClient().auth.getUser().then(({ data }) => setEmail(data.user?.email ?? null)); }, [load]);
  const running = runs.find((run) => run.status === "running");
  useEffect(() => { if (!running) return; const reload = window.setInterval(() => void load().catch((caught) => setError(caught.message)), 5_000); const clock = window.setInterval(() => setNow(Date.now()), 1_000); return () => { window.clearInterval(reload); window.clearInterval(clock); }; }, [running, load]);
  async function start() { setStarting(true); setError(null); try { const response = await fetch("/api/mhd-catalog-import", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "No se pudo iniciar la importación."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Error inesperado."); } finally { setStarting(false); } }
  const entity = running?.progress.entity ?? ""; const expected = Number(running?.progress.expected ?? 0); const count = Number(running?.record_counts?.[entity] ?? 0); const percent = expected ? Math.min(100, Math.round((count * 100) / expected)) : 0; const elapsed = running ? elapsedMs(running.started_at, null, now) : 0; const remaining = running && count > 0 && expected > count ? Math.round((elapsed / count) * (expected - count)) : null;
  return <div className="min-h-screen bg-zinc-50 lg:grid lg:grid-cols-[15rem_minmax(0,1fr)]"><AppSidebar active="mhdImport" userEmail={email} /><main className="mx-auto flex w-full max-w-5xl flex-col gap-7 px-6 pb-24 pt-28 sm:px-10 lg:mx-0 lg:py-16">
    <header><h1 className="text-4xl font-semibold tracking-tight text-zinc-950">Importar de MHD</h1><p className="mt-3 max-w-3xl text-zinc-600">Copia el catálogo completo desde la API de MHD a Supabase. La importación se valida antes de actualizar las tablas definitivas.</p></header>
    {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}
    <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">Importación completa</h2><p className="mt-1 text-sm text-zinc-600">Categorías, marcas, productos, precios y stock.</p></div><button onClick={start} disabled={Boolean(running) || starting} className="h-11 rounded-lg bg-emerald-700 px-5 font-medium text-white hover:bg-emerald-800 disabled:opacity-60">{running ? "Importación en curso…" : starting ? "Preparando…" : "Importar catálogo MHD"}</button></div>
      {running && <div className="mt-6 border-t border-zinc-100 pt-5"><div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1"><div><h3 className="font-semibold text-zinc-950">{labels[entity] ?? "Preparando importación"}</h3><p className="mt-1 text-sm text-zinc-600">Entidad {running.progress.entityIndex ?? "—"} de {running.progress.totalEntities ?? 5} · página {running.progress.page ?? "—"}</p></div><span className="text-sm font-semibold text-emerald-700">{percent}%</span></div><div className="mt-4"><div className="mb-2 flex justify-between text-sm font-medium text-zinc-700"><span>{count.toLocaleString("es-ES")} de {expected ? expected.toLocaleString("es-ES") : "…"} registros</span><span>{expected ? `${Math.max(0, expected - count).toLocaleString("es-ES")} pendientes` : "Calculando total…"}</span></div><div className="h-3 overflow-hidden rounded-full bg-zinc-100"><div className="h-full bg-emerald-600 transition-all" style={{ width: `${percent}%` }} /></div></div><p className="mt-3 text-sm text-zinc-600">Tiempo transcurrido: {formatDuration(elapsed)}{remaining !== null ? ` · restante estimado: ${formatDuration(remaining)} · final estimado: ${formatDate(new Date(now + remaining).toISOString())}` : " · calculando la estimación…"}</p></div>}
    </section>
    <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-baseline justify-between gap-4"><div><h2 className="text-xl font-semibold">Histórico</h2><p className="mt-1 text-sm text-zinc-600">Cada ejecución conserva sus resultados y la duración de cada parte.</p></div><span className="text-sm text-zinc-500">{runs.length} ejecuciones recientes</span></div><div className="mt-4 overflow-hidden rounded-xl border border-zinc-200"><ul className="divide-y divide-zinc-100">{runs.length ? runs.map((run) => <li key={run.id} className="p-4"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><StatusBadge status={run.status} /><time className="text-sm text-zinc-600">{formatDate(run.started_at)}</time><span className="text-sm text-zinc-600">Duración total: {formatDuration(elapsedMs(run.started_at, run.completed_at, now))}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-5">{Object.entries(labels).map(([key, label]) => <EntitySummary key={key} label={label} count={run.record_counts[key]} timing={run.progress.entity_timings?.[key]} now={now} active={run.status === "running" && run.progress.entity === key} />)}</div>{run.error_message && <p className="mt-3 text-sm text-red-700">{run.error_message}</p>}</li>) : <li className="p-4 text-sm text-zinc-500">Todavía no hay importaciones MHD.</li>}</ul></div></section>
  </main></div>;
}
function EntitySummary({ label, count, timing, now, active }: { label: string; count: number | undefined; timing: EntityTiming | undefined; now: number; active: boolean }) { const duration = timing ? formatDuration(elapsedMs(timing.started_at, timing.completed_at ?? null, now)) : "Pendiente"; return <div className={`rounded-xl p-3 text-sm ${active ? "bg-emerald-50 ring-1 ring-emerald-200" : "bg-zinc-50"}`}><span className="block text-zinc-500">{label}</span><b className="mt-1 block text-zinc-900">{count?.toLocaleString("es-ES") ?? "—"}</b><span className="mt-1 block text-xs text-zinc-500">{timing ? `${timing.completed_at ? "Duración" : "En curso"}: ${duration}` : duration}</span></div>; }
function StatusBadge({ status }: { status: Run["status"] }) { const detail = status === "completed" ? ["Completada", "bg-emerald-50 text-emerald-800"] : status === "failed" ? ["Con error", "bg-red-50 text-red-800"] : ["En curso", "bg-amber-50 text-amber-800"]; return <span className={`rounded-full px-2.5 py-1 text-sm font-medium ${detail[1]}`}>{detail[0]}</span>; }
function elapsedMs(startedAt: string, completedAt: string | null, now: number) { return Math.max(0, (completedAt ? new Date(completedAt).getTime() : now) - new Date(startedAt).getTime()); }
function formatDuration(milliseconds: number) { const seconds = Math.round(Math.max(0, milliseconds) / 1_000); if (seconds < 60) return `${seconds} s`; const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); const rest = seconds % 60; return hours ? `${hours} h ${minutes} min${rest ? ` ${rest} s` : ""}` : `${minutes} min${rest ? ` ${rest} s` : ""}`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-ES", { timeZone: "Europe/Madrid", dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
