"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Run = { id: string; mode: "id" | "from_date" | "latest"; parameters: Record<string, unknown>; status: "queued" | "running" | "paused" | "stopped" | "completed" | "failed"; total_count: number; processed_count: number; created_count: number; existing_count: number; error_count: number; started_at: string | null; finished_at: string | null; created_at: string };
type ImportEvent = { id: number; outcome: "created" | "existing" | "error" | "status"; level: "info" | "success" | "warning" | "error"; prestashop_customer_id: number | null; customer_email: string | null; shopify_customer_id: string | null; message: string; created_at: string };

export default function ExecutionPage() {
  const { id } = useParams<{ id: string }>();
  const [run, setRun] = useState<Run | null>(null);
  const [events, setEvents] = useState<ImportEvent[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const supabase = createClient(); Promise.all([supabase.from("customer_import_runs").select("*").eq("id", id).maybeSingle(), supabase.from("customer_import_events").select("*").eq("run_id", id).order("id", { ascending: true })]).then(([runResult, eventsResult]) => { if (runResult.error || !runResult.data) setError("No se encontró esta ejecución."); else setRun(runResult.data as Run); setEvents((eventsResult.data ?? []) as ImportEvent[]); }); }, [id]);
  if (error) return <main className="mx-auto w-full max-w-4xl px-6 py-16"><a href="/importaciones-masivas#historial" className="text-emerald-700 underline">← Volver a ejecuciones</a><p className="mt-6 rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</p></main>;
  if (!run) return <main className="mx-auto w-full max-w-4xl px-6 py-16 text-zinc-500">Cargando ejecución…</main>;
  return <main className="mx-auto w-full max-w-5xl px-6 py-12 pb-16"><a href="/importaciones-masivas#historial" className="text-sm font-medium text-emerald-700 underline underline-offset-2">← Volver a ejecuciones</a><header className="mt-6"><p className="text-sm font-semibold tracking-[0.18em] text-emerald-700 uppercase">Historial</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{scopeLabel(run)}</h1><p className="mt-3 text-zinc-600">Iniciada: {new Date(run.created_at).toLocaleString("es-ES")} · <span className="font-medium">{statusLabel(run.status)}</span> · {durationLabel(run)}</p></header><section className="mt-8 grid gap-3 sm:grid-cols-4"><Counter label="Procesados" value={`${run.processed_count}/${run.total_count}`} /><Counter label="Creados" value={run.created_count} /><Counter label="Ya existían" value={run.existing_count} /><Counter label="Errores" value={run.error_count} /></section><section className="mt-8 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Registro completo</h2><ul className="mt-4 divide-y divide-zinc-100 overflow-hidden rounded-xl border border-zinc-200">{events.map((event) => <li key={event.id} className="p-4 text-sm"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><span className={`font-semibold ${event.outcome === "created" ? "text-emerald-700" : event.outcome === "error" ? "text-red-700" : event.outcome === "existing" ? "text-amber-700" : "text-zinc-700"}`}>{event.outcome === "created" ? "Creado" : event.outcome === "existing" ? "Ya existía" : event.outcome === "error" ? "Error" : "Estado"}</span>{event.prestashop_customer_id && <span>PS #{event.prestashop_customer_id}</span>}{event.customer_email && <span className="text-zinc-600">{event.customer_email}</span>}{event.shopify_customer_id && <a href={shopifyUrl(event.shopify_customer_id)} target="_blank" rel="noreferrer" className="text-emerald-700 underline">Abrir cliente en Shopify</a>}<time className="ml-auto text-zinc-400">{new Date(event.created_at).toLocaleString("es-ES")}</time></div><p className="mt-1 text-zinc-600">{event.message}</p></li>)}</ul></section></main>;
}

function scopeLabel(run: Run) { return run.mode === "id" ? `Cliente #${run.parameters.customerId}` : run.mode === "from_date" ? `Desde ${String(run.parameters.fromDate).slice(0, 10)}` : `Últimos ${run.parameters.latest} clientes`; }
function statusLabel(status: Run["status"]) { return ({ queued: "En cola", running: "En marcha", paused: "Pausada", stopped: "Detenida", completed: "Completada", failed: "Con error" } as const)[status]; }
function durationLabel(run: Run) { if (!run.started_at) return "Sin iniciar"; const end = run.finished_at ? new Date(run.finished_at).getTime() : Date.now(); const seconds = Math.max(0, Math.round((end - new Date(run.started_at).getTime()) / 1_000)); return seconds < 60 ? `Duración: ${seconds} s` : `Duración: ${Math.floor(seconds / 60)} min ${seconds % 60 ? `${seconds % 60} s` : ""}`; }
function shopifyUrl(id: string) { return `https://admin.shopify.com/store/electronica-vicente/customers/${id.split("/").pop()}`; }
function Counter({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-sm text-zinc-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>; }
