-- Correspondencias obtenidas de Shopify (código oficial) y de MHD.
-- Las regiones con active=false existen en ambos catálogos pero MHD indica
-- que no tiene envío disponible; se conservan para explicar el bloqueo.
insert into public.mhd_order_countries (iso_2, mhd_country_id, name, shipping_enabled)
values ('PT', 620, 'Portugal', true)
on conflict (iso_2) do update
set mhd_country_id = excluded.mhd_country_id,
    name = excluded.name,
    shipping_enabled = excluded.shipping_enabled,
    updated_at = now();

insert into public.mhd_order_province_mappings
  (country_iso_2, shopify_province_code, shopify_province_name, mhd_province_id, mhd_province_name, active)
values
  ('ES', 'C',  'A Coruña', 15, 'A Coruña', true),
  ('ES', 'VI', 'Álava', 1, 'Álava', true),
  ('ES', 'AB', 'Albacete', 2, 'Albacete', true),
  ('ES', 'A',  'Alicante', 3, 'Alicante', true),
  ('ES', 'AL', 'Almería', 4, 'Almería', true),
  ('ES', 'O',  'Asturias', 33, 'Asturias', true),
  ('ES', 'AV', 'Ávila', 5, 'Ávila', true),
  ('ES', 'BA', 'Badajoz', 6, 'Badajoz', true),
  ('ES', 'PM', 'Balears', 7, 'Baleares', true),
  ('ES', 'B',  'Barcelona', 8, 'Barcelona', true),
  ('ES', 'BI', 'Vizcaya', 48, 'Bizkaia', true),
  ('ES', 'BU', 'Burgos', 9, 'Burgos', true),
  ('ES', 'CC', 'Cáceres', 10, 'Cáceres', true),
  ('ES', 'CA', 'Cádiz', 11, 'Cádiz', true),
  ('ES', 'S',  'Cantabria', 39, 'Cantabria', true),
  ('ES', 'CS', 'Castellón', 12, 'Castellón', true),
  ('ES', 'CE', 'Ceuta', 51, 'Ceuta', false),
  ('ES', 'CR', 'Ciudad Real', 13, 'Ciudad Real', true),
  ('ES', 'CO', 'Córdoba', 14, 'Córdoba', true),
  ('ES', 'CU', 'Cuenca', 16, 'Cuenca', true),
  ('ES', 'SS', 'Guipúzcoa', 20, 'Gipuzkoa', true),
  ('ES', 'GI', 'Girona', 17, 'Girona', true),
  ('ES', 'GR', 'Granada', 18, 'Granada', true),
  ('ES', 'GU', 'Guadalajara', 19, 'Guadalajara', true),
  ('ES', 'H',  'Huelva', 21, 'Huelva', true),
  ('ES', 'HU', 'Huesca', 22, 'Huesca', true),
  ('ES', 'J',  'Jaén', 23, 'Jaén', true),
  ('ES', 'LO', 'La Rioja', 26, 'La Rioja', true),
  ('ES', 'GC', 'Las Palmas', 35, 'Las Palmas', false),
  ('ES', 'LE', 'León', 24, 'León', true),
  ('ES', 'L',  'Lleida', 25, 'Lleida', true),
  ('ES', 'LU', 'Lugo', 27, 'Lugo', true),
  ('ES', 'M',  'Madrid', 28, 'Madrid', true),
  ('ES', 'MA', 'Málaga', 29, 'Málaga', true),
  ('ES', 'ML', 'Melilla', 52, 'Melilla', false),
  ('ES', 'MU', 'Murcia', 30, 'Murcia', true),
  ('ES', 'NA', 'Navarra', 31, 'Navarra', true),
  ('ES', 'OR', 'Ourense', 32, 'Ourense', true),
  ('ES', 'P',  'Palencia', 34, 'Palencia', true),
  ('ES', 'PO', 'Pontevedra', 36, 'Pontevedra', true),
  ('ES', 'SA', 'Salamanca', 37, 'Salamanca', true),
  ('ES', 'TF', 'Santa Cruz de Tenerife', 38, 'Santa Cruz de Tenerife', false),
  ('ES', 'SG', 'Segovia', 40, 'Segovia', true),
  ('ES', 'SE', 'Sevilla', 41, 'Sevilla', true),
  ('ES', 'SO', 'Soria', 42, 'Soria', true),
  ('ES', 'T',  'Tarragona', 43, 'Tarragona', true),
  ('ES', 'TE', 'Teruel', 44, 'Teruel', true),
  ('ES', 'TO', 'Toledo', 45, 'Toledo', true),
  ('ES', 'V',  'Valencia', 46, 'Valencia', true),
  ('ES', 'VA', 'Valladolid', 47, 'Valladolid', true),
  ('ES', 'ZA', 'Zamora', 49, 'Zamora', true),
  ('ES', 'Z',  'Zaragoza', 50, 'Zaragoza', true),
  ('PT', 'PT-20', 'Açores', 103, 'Açores', false),
  ('PT', 'PT-01', 'Aveiro', 91, 'Aveiro', true),
  ('PT', 'PT-02', 'Beja', 101, 'Beja', true),
  ('PT', 'PT-03', 'Braga', 95, 'Braga', true),
  ('PT', 'PT-04', 'Bragança', 98, 'Bragança', true),
  ('PT', 'PT-05', 'Castelo Branco', 99, 'Castelo Branco', true),
  ('PT', 'PT-06', 'Coimbra', 90, 'Coimbra', true),
  ('PT', 'PT-07', 'Évora', 89, 'Évora', true),
  ('PT', 'PT-08', 'Faro', 102, 'Faro', true),
  ('PT', 'PT-09', 'Guarda', 93, 'Guarda', true),
  ('PT', 'PT-10', 'Leiria', 88, 'Leiria', true),
  ('PT', 'PT-11', 'Lisboa', 85, 'Lisboa', true),
  ('PT', 'PT-30', 'Madeira', 104, 'Madeira', false),
  ('PT', 'PT-12', 'Portalegre', 100, 'Portalegre', true),
  ('PT', 'PT-13', 'Porto', 94, 'Porto', true),
  ('PT', 'PT-14', 'Santarém', 86, 'Santarém', true),
  ('PT', 'PT-15', 'Setúbal', 87, 'Setúbal', true),
  ('PT', 'PT-16', 'Viana do Castelo', 97, 'Viana do Castelo', true),
  ('PT', 'PT-17', 'Vila Real', 96, 'Vila Real', true),
  ('PT', 'PT-18', 'Viseu', 92, 'Viseu', true)
on conflict (country_iso_2, shopify_province_code) do update
set shopify_province_name = excluded.shopify_province_name,
    mhd_province_id = excluded.mhd_province_id,
    mhd_province_name = excluded.mhd_province_name,
    active = excluded.active;
